name: triptip
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  carousel_slider: ^5.0.0
  dio: ^5.0.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  flutter_bloc: ^8.1.6
  expandable_text: ^2.3.0
  equatable: ^2.0.5
  image_picker: ^1.0.7
  http_parser: ^4.0.2
  cached_network_image: ^3.2.0
  supabase_flutter: ^2.8.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/
